name: decor
description: Flutter way HTML builder package for Dart.
version: 1.0.0
repository: https://github.com/alierkanimrek/decor

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
